services:
  db:
    image: postgres
    volumes:
     - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  web:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 3000 -b 0.0.0.0"
    stdin_open: true
    tty: true
    environment:
      - DATABASE_HOST=db
    env_file:
      - .env

volumes:
  db: